title:            Cocktails & Coffee 
byline:           Jimmy Little
description:      Internet ramblings fueled by adult beverages.
# put your disqus here
disqus_shortname: 
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             https://s3-us-west-2.amazonaws.com/www.jimmylittle.com/site_images/sitelogo70.png # logo visible in the topbar


url: http://cocktailsandcoffee.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
#  - title: 'Tags'
#    url: '/tags'
  - title: 'Archive'
    url: '/categories'
    type: 'categories'

# Owner/author information
owner:
  name:           Jimmy 
  site:           http://jimmylittle.com
  avatar:         images/avatar.jpg
  bio:            "I write stuff sometimes."
  email:          thejimmylittle@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter:  # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: 

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: jimmylittle

# Social networking links used in author block underneath posts. Update and remove as you like.
#social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
#background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-76295212-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


include: [".htaccess"]
exclude: ["/vendor", "lib", "/vendor", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

